spring.application.name=gateway
spring.config.import=optional:configserver:http://localhost:8084
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/fitness-app/protocol/openid-connect/certs


# redirect to user service
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/user/**


# redirect to activity service
spring.cloud.gateway.server.webflux.routes[1].id=activity-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ACTIVITY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/activities/**

# redirect to AI service
spring.cloud.gateway.server.webflux.routes[2].id=ai-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://AI-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/recommendation/**