spring.application.name=gateway
spring.config.import=optional:configserver:http://localhost:8084

# redirect to user service
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**